name: Deploy to Google Cloud Storage
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Authenticated with Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Remove all current files
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: -m rm gs://bruno.sabot.me/**

      - name: Copy root files file
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: -m  cp -a public-read -r * gs://bruno.sabot.me

      - name: Copy new files with cache control header
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: -m -h "Cache-Control:public,max-age=31536000" cp -a public-read -r static/* gs://bruno.sabot.me
